# Amazon SageMaker Autopilot Data Exploration Report

This report contains insights about the dataset you provided as input to the AutoML job.
This data report was generated by **automl-dm-1651584516** AutoML job.
To check for any issues with your data and possible improvements that can be made to it,
consult the sections below for guidance.
You can use information about the predictive power of each feature in the **Data Sample** section and
from the correlation matrix in the **Cross Column Statistics** section to help select a subset of the data
that is most significant for making predictions.

**Note**: SageMaker Autopilot data reports are subject to change and updates.
It is not recommended to parse the report using automated tools, as they may be impacted by such changes.

## Dataset Summary
**Note**: due to timeouts while processing your data, it's possible that some issues with your data were not detected.
See further details in the sections below. To avoid such timeouts, try reducing the number of columns in the dataset.



<br>
<b>Dataset Properties</b>
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>Rows</th>
      <th>Columns</th>
      <th>Duplicate rows</th>
      <th>Target column</th>
      <th>Missing target values</th>
      <th>Invalid target values</th>
      <th>Detected problem type</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>7110</td>
      <td>2</td>
      <td>0.03%</td>
      <td>sentiment</td>
      <td>0.00%</td>
      <td>0.00%</td>
      <td>MulticlassClassification</td>
    </tr>
  </tbody>
</table>
</div>
<b>Detected Column Types</b>
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Numeric</th>
      <th>Categorical</th>
      <th>Text</th>
      <th>Datetime</th>
      <th>Sequence</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Column Count</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>Percentage</th>
      <td>0.00%</td>
      <td>0.00%</td>
      <td>100.00%</td>
      <td>0.00%</td>
      <td>0.00%</td>
    </tr>
  </tbody>
</table>
</div>

---

## Report Contents

1. [Target Analysis](#Target-Analysis)<br>
1. [Data Sample](#Data-Sample)<br>
1. [Duplicate Rows](#Duplicate-Rows)<br>
1. [Cross Column Statistics](#Cross-Column-Statistics)<br>
1. [Anomalous Rows](#Anomalous-Rows)<br>
1. [Missing Values](#Missing-Values)<br>
1. [Cardinality](#Cardinality)<br>
1. [Descriptive Stats](#Descriptive-Stats)<br>
1. [Definitions](#Definitions)<br>
---

### Target Analysis



The column **sentiment** is used as the target column.
See the distribution of values (labels) in the target column below:

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: left;">
      <th>Number of Classes</th>
      <th>Invalid Percentage</th>
      <th>Missing Percentage</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>3</td>
      <td>0.00%</td>
      <td>0.00%</td>
    </tr>
  </tbody>
</table>
</div>
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: left;">
      <th>Target Label</th>
      <th>Frequency Percentage</th>
      <th>Label Count</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0</td>
      <td>33.33%</td>
      <td>2370</td>
    </tr>
    <tr>
      <td>1</td>
      <td>33.33%</td>
      <td>2370</td>
    </tr>
    <tr>
      <td>-1</td>
      <td>33.33%</td>
      <td>2370</td>
    </tr>
  </tbody>
</table>
</div>

<center><figure>
  <img src="" style="height: 250px; width: auto;">
  <figcaption>Histogram of the target column labels.</figcaption>
</figure></center>

## Data Sample

The following table contains a random sample of **10** rows from the dataset.
The top two rows provide the type and prediction power of each column.
Verify the input headers correctly align with the columns of the dataset sample.
If they are incorrect, update the header names of your input dataset in Amazon Simple Storage Service (Amazon S3).

<div style="overflow-y:auto;">
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: left;">
      <th></th>
      <th>sentiment</th>
      <th>review_body</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Prediction Power</th>
      <td>-</td>
      <td>0.300633</td>
    </tr>
    <tr>
      <th>Column Types</th>
      <td>-</td>
      <td>text</td>
    </tr>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>I love the way the dress fit definitely a flip flop by the poolside bar dress. i ordered the mango colored one and was disappointed that the color resembled a dark squash orange and not as bright as it looked in picture. i think it will look nice with a tan so i will keep it. wouldn't plan to dress it up too much because it will definitely wrinkle ! i am a petite 5'4 and got the regular and it fits just above my knees which is good for my taste!</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>Great pants. i'm 5'6 and about 130. the size 2 fit nice at the waist and loose in the thigh. they hit right at the ankle. the colors are nice/ muted. the details are great. overall great pants.</td>
    </tr>
    <tr>
      <th>2</th>
      <td>-1</td>
      <td>If you have any cleavage this dress will look awful. the ties drop pretty low &amp; look trashy over cleavage. recommend otherwise - good fabric cool look</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0</td>
      <td>Other reviews are correct. but this has potential to look as good as on the model - structure and quality of the cotton are very flattering. makes legs look miles long. however this fits very tight  allows no room for extra tummy  hips  booty  or thighs. i ordered a s (i'm usually a 4) - was able to get it on (step into it from the top)  but felt a little self conscious about how tight the fit was. if there was an m  would have definitely sized up  as i really liked the look.</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1</td>
      <td>This dress is even more gorgeous in person! i had seen in the spring catalog but liked it even more when i spotted it at my local store. i have been searching for the perfect ivory crochet or lace dress each summer for the past few years. i think i have finally found "the one'! i should note i am 5'9" and this dress goes all the way to my knees. it may swallow someone on the shorter side.</td>
    </tr>
    <tr>
      <th>5</th>
      <td>-1</td>
      <td>I should have paid closer attention to the other reviews. i could barely get this blouse over my head! after getting it on  the armholes too are very small. the blouse other than that is pretty and very girlie. i love the pleating and dolman sleeves but i was strangled around my neck. i tried the small but think a medium wouldn't have been much better. it needs a button opening on neck and sleeves. i would have to put this on before makeup or doing my hair.   if you have a tiny head and penc...</td>
    </tr>
    <tr>
      <th>6</th>
      <td>1</td>
      <td>I have worn these exclusively for the past couple of years. they fit great (tts)  stay put  and wear very well. these are well worth the price.</td>
    </tr>
    <tr>
      <th>7</th>
      <td>1</td>
      <td>These leggings are so comfortable and luxurious.  when i opened the package i knew i was in trouble.  they are comfortable and beautiful.  a perfect piece for any wardrobe.</td>
    </tr>
  </tbody>
</table>
</div>
<div style="overflow-x:auto;">

## Duplicate Rows


<div class="alert alert-secondary"> ⚠️ <strong> Low severity insight: “Duplicate rows” </strong> <br>
0.03% of the rows were found to be duplicates when testing a random sample of 7110 rows from the dataset. Some data sources could include valid duplicates, but in some cases these duplicates could point to problems in data collection. Unintended duplicate rows could disrupt the automatic hyperparameter tuning of Amazon SageMaker Autopilot and result in sub-par model. Thus should be removed for more accurate results. This preprocessing can be done with Amazon SageMaker Data Wrangler using the “Drop duplicates” transform under “Manage rows”.
</div>

A sample of duplicate rows is presented below.
The number of occurrences of a row is given in left most **Duplicate count** column.
<div style="overflow-y:auto;">
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: left;">
      <th>Duplicate count</th>
      <th>review_body</th>
      <th>sentiment</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>2</td>
      <td>I purchased this and another eva franco dress during retailer's recent 20% off sale. i was looking for dresses that were work appropriate  but that would also transition well to happy hour or date night. they both seemed to be just what i was looking for. i ordered a 4 regular and a 6 regular  as i am usually in between sizes. the 4 was definitely too small. the 6 fit  technically  but was very ill fitting. not only is the dress itself short  but it is very short-waisted. i am only 5'3"  but...</td>
      <td>-1</td>
    </tr>
  </tbody>
</table>
</div>
<div style="overflow-x:auto;">

## Cross Column Statistics

Amazon SageMaker Autopilot calculates Pearson’s correlation between columns in your dataset.
Removing highly correlated columns can reduce overfitting and training time.
Pearson’s correlation is in the range [-1, 1] where 0 implies no correlation, 1 implies perfect correlation,
and -1 implies perfect inverse correlation.

No correlation scores were calculated because the calculation took too long to complete.

### Anomalous Rows

Anomalous rows are detected using the Isolation forest algorithm on a sample of
**7110**
randomly chosen
rows after basic preprocessing. The isolation forest algorithm associates an anomaly score to each row of the dataset
it is trained on. Rows with negative anomaly scores are usually considered anomalous and rows with positive anomaly
scores are considered non-anomalous. When investigating an anomalous row, look for any unusual values -
in particular any that might have resulted from errors in the gathering and processing of data.
Deciphering whether a row is indeed anomalous, contains errors, or is in fact valid requires domain knowledge and
application of business logic.

There were no anomalous rows found in the dataset.

### Missing Values
Within the data sample, the following columns contained missing values, such as: `nan`, white spaces, or empty fields.

SageMaker Autopilot will attempt to fill in missing values using various techniques. For example,
missing values can be replaced with a new 'unknown' category for `Categorical` features
and missing `Numerical` values can be replaced with the **mean** or **median** of the column.

We found **0 of the 2** of the columns contained missing values.

### Cardinality
For `String` features, it is important to count the number of unique values to determine whether to treat a feature as `Categorical` or `Text`
and then processes the feature according to its type.

For example, SageMaker Autopilot counts the number of unique entries and the number of unique words.
The following string column would have **3** total entries, **2** unique entries, and **3** unique words.

|       | String Column     |
|-------|-------------------|
| **0** | "red blue"        |
| **1** | "red blue"        |
| **2** | "red blue yellow" |

If the feature is `Categorical`, SageMaker Autopilot can look at the total number of unique entries and transform it using techniques such as one-hot encoding.
If the field contains a `Text` string, we look at the number of unique words, or the vocabulary size, in the string.
We can use the unique words to then compute text-based features, such as Term Frequency-Inverse Document Frequency (tf-idf).

**Note:** If the number of unique values is too high, we risk data transformations expanding the dataset to too many features.
In that case, SageMaker Autopilot will attempt to reduce the dimensionality of the post-processed data,
such as by capping the number vocabulary words for tf-idf, applying Principle Component Analysis (PCA), or other dimensionality reduction techniques.

The table below shows **2 of the 2** columns ranked by the number of unique entries.

<div class="alert alert-info"> 💡 <strong> Suggested Action Items</strong>

- Verify the number of unique values of a feature is as expected.
    One explanation for unexpected number of unique values could be multiple encodings of a value.
    For example `US` and `U.S.` will count as two different words.
    You could correct the error at the data source or pre-process your dataset in your S3 bucket.
- If the number of unique values seems too high for Categorical variables,
    investigate if multiple unique values can be grouped into a smaller set of possible values.
</div>

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Number of Unique Entries</th>
      <th>Number of Unique Words (if Text)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>sentiment</th>
      <td>3</td>
      <td>n/a</td>
    </tr>
    <tr>
      <th>review_body</th>
      <td>7108</td>
      <td>17986</td>
    </tr>
  </tbody>
</table>
</div>

### Descriptive Stats
For each of the input features that has at least one numeric value, several descriptive statistics are computed from the data sample.

SageMaker Autopilot may treat numerical features as `Categorical` if the number of unique entries is sufficiently low.
For `Numerical` features, we may apply numerical transformations such as normalization, log and quantile transforms,
and binning to manage outlier values and difference in feature scales.

We found **1 of the 2** columns contained at least one numerical value.
The table below shows the **1** columns which have the largest percentage of numerical values.
Percentage of outliers is calculated only for columns which Autopilot detected to be of numeric type. Percentage of outliers is
not calculated for the target column.

<div class="alert alert-info"> 💡 <strong> Suggested Action Items</strong>

- Investigate the origin of the data field. Are some values non-finite (e.g. infinity, nan)?
    Are they missing or is it an error in data input?
- Missing and extreme values may indicate a bug in the data collection process.
    Verify the numerical descriptions align with expectations.
    For example, use domain knowledge to check that the range of values for a feature meets with expectations.
</div>


<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>% of Numerical Values</th>
      <th>Mean</th>
      <th>Median</th>
      <th>Min</th>
      <th>Max</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>sentiment</th>
      <td>100.0%</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>-1.0</td>
      <td>1.0</td>
    </tr>
  </tbody>
</table>
</div>

## Definitions

### Feature types

**Numeric:** Numeric values, either floats or integers. For example: age, income. When training a machine learning model, it is assumed that numeric values are ordered and a distance is defined between them. For example, 3 is closer to 4 than to 10 and 3 < 4 < 10.

**Categorical:** The column entries belong to a set of unique values that is usually much smaller than number of rows in the dataset. For example, a column from datasets with 100 rows with the unique values "Dog", "Cat" and "Mouse". The values could be numeric, textual, or combination of both. For example, "Horse", "House", 8, "Love" and 3.1 are
all valid values and can be found in the same categorical column. When manipulating column of categorical values, a machine learning model does not assume that they are ordered or that distance function is defined on them, even if all of the values are numbers.

**Binary:** A special case of categorical column for which the cardinality of the set of unique values is 2.

**Text:** A text column that contains many non-numeric unique values, often a human readable text. In extreme cases, all the elements of the column are unique, so no two entries are the same.

**Datetime:** This column contains date and/or time information.

### Feature statistics

**Prediction power:** Prediction power of a column (feature) is a measure of how useful it is for predicting the target variable. It is measured using a stratified split into 80%/20% training and validation folds. We fit a model for each feature separately on the training fold after applying minimal feature pre-processing and measure prediction performance on the validation data. The scores are normalized to the range [0,1]. A higher prediction power score near 1 indicate that a column is more useful for predicting the target on its own. A lower score near 0 indicate that a column contains little useful information for predicting the target on their own. Although it is possible that a column that is uninformative on its own can be useful in predicting the target when used in tandem with other features, a low score usually indicates the feature is redundant. A score of 1 implies perfect predictive abilities, which often indicates an error called target leakage. The cause is typically a column present in dataset that is hard or impossible to obtain at prediction time, such as a duplicate of the target.

**Outliers:** Outliers are detected using two statistics that are robust to outliers: median and robust standard deviation (RSTD). RSTD is derived by clipping the feature values to the range [5 percentile, 95 percentile] and calculating the standard deviation of the clipped vector. All values larger than median + 5 * RSTD or smaller than median - 5 * RSTD are considered to be outliers.

**Skew:** Skew measures the symmetry of the distribution and is defined as the third moment of the distribution divided by the third power of the standard deviation. The skewness of the normal distribution or any other symmetric distribution is zero. Positive values imply that the right tail of the distribution is longer than the left tail. Negative values imply that the left tail of the distribution is longer than the right tail. As a thumb rule, a distribution is considered skewed when the absolute value of the skew is larger than 3.

**Kurtosis:** Pearson's kurtosis measures the heaviness of the tail of the distribution and is defined as the fourth moment of the distribution divided by the fourth power of the standard deviation. The kurtosis of the normal distribution is 3. Thus, kurtosis values lower than 3 imply that the distribution is more concentrated around the mean and the tails are lighter than the tails of the normal distribution. Kurtosis values higher than 3 imply heavier tails than the normal distribution or that the data contains outliers.

**Missing Values:** Empty strings and strings composed of only white spaces are considered missing.

**Valid values:**

* **Numeric features / regression target:** All values that could be casted to finite floats are valid. Missing values are not valid.
* **Categorical / binary / text features / classification target:** All values that are not missing are valid.
* **Datetime features:** All values that could be casted to datetime object are valid. Missing values are not valid.

**Invalid values:** values that are either missing or that could not be casted to the desired type. See the definition of valid values for more information